
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yml

images:
  - name: yossefazozz/argocd_lab
    newTag: "1"

commonLabels:
  env: dev

nameSuffix: -prod
